### ISSUE TITLE
Sorting weekdays correctly

### ISSUE THREAD

**Issue by erikhhhh** [groodlooker/vega-lite#13]
Currently weekday fields in Looker are sorted alphabetically. 

Can you make it to sort from Mon-Sun or ability to choose how weekdays are sorted?

https://vega.github.io/vega-lite/docs/sort.html

**Comment by groodlooker** [comment]
Taking a look at this. Unfortunately there is a bug in Vega-Lite (or limitation in the underlying Vega library really) that prevents multi-layered charts (labels are a layer in Vega) from being sorted in any way other than their natural order. I'll publish a fix soon that will sort it correctly as long as the chart only has one layer.

**Comment by groodlooker** [comment]
Hey @erikhhhh, sorry this took so long. Turned out to be pretty tricky but it should be working now for both Month Name and Week Day. I put it into a beta file for now, mind testing it out? I had to make some fairly significant changes to want to make sure no un-intended side effects.

Also, you need to **add new versions of vega dependencies** for this to work. I replaced the ones on the readme.

**Comment by erikhhhh** [comment]
![image](https://user-images.githubusercontent.com/11735168/54083884-32ba3280-4332-11e9-85b8-79a7f9964f11.png)

Looks like legends and stacked charts are not working correctly. If I put weekdays to X-axis then works as expected.
